insert into Country (CountryName) values ('Indonesia');
insert into Country (CountryName) values ('Sri Lanka');
insert into Country (CountryName) values ('India');
insert into Country (CountryName) values ('Thailand');
insert into Country (CountryName) values ('Singapore');
insert into Country (CountryName) values ('United States of America');
insert into Country (CountryName) values ('Mexico');
insert into Country (CountryName) values ('England');
insert into Country (CountryName) values ('France');
insert into Country (CountryName) values ('Italy');
insert into Country (CountryName) values ('Germany');
insert into Country (CountryName) values ('Spain');
insert into Country (CountryName) values ('Netherlands');
insert into Country (CountryName) values ('Turkey');
insert into Country (CountryName) values ('United Arab Emirates');
insert into Country (CountryName) values ('Qatar');
insert into Country (CountryName) values ('Japan');
insert into Country (CountryName) values ('South Korea');
insert into Country (CountryName) values ('China');
insert into Country (CountryName) values ('Australia');

insert into State (StateName) values ('Delhi');
insert into State (StateName) values ('Maharashtra');
insert into State (StateName) values ('Tamil Nadu');
insert into State (StateName) values ('New York');
insert into State (StateName) values ('Illinois');
insert into State (StateName) values ('California');
insert into State (StateName) values ('Mexico City');
insert into State (StateName) values ('Bavaria');
insert into State (StateName) values ('Hesse');
insert into State (StateName) values ('New South Wales');
insert into State (StateName) values ('Victoria');
insert into State (StateName) values ('Delhi');
insert into State (StateName) values ('Maharashtra');
insert into State (StateName) values ('Tamil Nadu');
insert into State (StateName) values ('New York');
insert into State (StateName) values ('Illinois');
insert into State (StateName) values ('California');
insert into State (StateName) values ('Mexico City');
insert into State (StateName) values ('Bavaria');
insert into State (StateName) values ('Hesse');
insert into State (StateName) values ('New South Wales');
insert into State (StateName) values ('Victoria');
#####
insert into State (StateName) values ('Delhi');
insert into State (StateName) values ('Maharashtra');
insert into State (StateName) values ('Tamil Nadu');
insert into State (StateName) values ('New York');
insert into State (StateName) values ('Illinois');
insert into State (StateName) values ('California');
insert into State (StateName) values ('Mexico City');
insert into State (StateName) values ('Bavaria');
insert into State (StateName) values ('Hesse');
insert into State (StateName) values ('New South Wales');
insert into State (StateName) values ('Victoria');
insert into State (StateName) values ('Delhi');
insert into State (StateName) values ('Maharashtra');
insert into State (StateName) values ('Tamil Nadu');
insert into State (StateName) values ('New York');
insert into State (StateName) values ('Illinois');
insert into State (StateName) values ('California');
insert into State (StateName) values ('Mexico City');
insert into State (StateName) values ('Bavaria');
insert into State (StateName) values ('Hesse');
insert into State (StateName) values ('New South Wales');
insert into State (StateName) values ('Victoria');

insert into City (CityName) values ('Tangerang');
insert into City (CityName) values ('Badung');
insert into City (CityName) values ('Katunayake');
insert into City (CityName) values ('Mattala');
insert into City (CityName) values ('Palam');
insert into City (CityName) values ('Mumbai');
insert into City (CityName) values ('Chennai');
insert into City (CityName) values ('Bangkok');
insert into City (CityName) values ('Changi');
insert into City (CityName) values ('New York City');
insert into City (CityName) values ('Chicago');
insert into City (CityName) values ('Los Angeles');
insert into City (CityName) values ('San Francisco');
insert into City (CityName) values ('Venustiano Carranza');
insert into City (CityName) values ('London');
insert into City (CityName) values ('Paris');
insert into City (CityName) values ('Rome');
insert into City (CityName) values ('Munich');
insert into City (CityName) values ('Frankfurt');
insert into City (CityName) values ('Madrid');
insert into City (CityName) values ('Barcelona');
insert into City (CityName) values ('Amsterdam');
insert into City (CityName) values ('Istanbul');
insert into City (CityName) values ('Dubai');
insert into City (CityName) values ('Doha');
insert into City (CityName) values ('Tokyo');
insert into City (CityName) values ('Seoul');
insert into City (CityName) values ('Guangzhou');
insert into City (CityName) values ('Shenzhen');
insert into City (CityName) values ('Chengdu');
insert into City (CityName) values ('Beijing');
insert into City (CityName) values ('Hong Kong');
insert into City (CityName) values ('Sydney');
insert into City (CityName) values ('Melbourne');

insert into Exist (Parent, Child, ParentType, ChildType) values (1, 1, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (1, 2, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (2, 3, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (2, 4, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (1, 5, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (3, 1, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (2, 6, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (3, 2, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (3, 7, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (3, 3, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (4, 8, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (5, 9, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (4, 10, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (6, 4, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (5, 11, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (6, 5, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (6, 12, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (6, 6, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (6, 13, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (7, 14, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (7, 7, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (8, 15, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (9, 16, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (10, 17, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (8, 18, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (11, 8, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (9, 19, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (11, 9, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (12, 20, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (12, 21, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (13, 22, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (14, 23, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (15, 24, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (16, 25, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (17, 26, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (18, 27, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (19, 28, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (19, 29, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (19, 30, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (19, 31, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (19, 32, 'Country', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (10, 33, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (20, 10, 'Country', 'State');
insert into Exist (Parent, Child, ParentType, ChildType) values (11, 34, 'State', 'City');
insert into Exist (Parent, Child, ParentType, ChildType) values (20, 11, 'Country', 'State');

insert into Airport values ('CGK', 'Soekarno-Hatta International Airport', '1');
insert into Airport values ('DPS', 'I Gusti Ngurah Rai International Airport', '2');
insert into Airport values ('BIA', 'Bandaranaike International Airport', '3');
insert into Airport values ('HRI', 'Mattala Rajapaksa International Airport', '4');
insert into Airport values ('DEL', 'Indira Gandhi International Airport', '5');
insert into Airport values ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', '6');
insert into Airport values ('MAA', 'Chennai International Airport', '7');
insert into Airport values ('BKK', 'Suvarnabhumi Airport', '8');
insert into Airport values ('DMK', 'Don Mueang International Airport', '8');
insert into Airport values ('SIN', 'Singapore Changi Airport', '9');
insert into Airport values ('JFK', 'John F. Kennedy International Airport', '10');
insert into Airport values ('ORD', "Chicago O'Hare International Airport", '11');
insert into Airport values ('LAX', 'Los Angeles International Airport', '12');
insert into Airport values ('SFO', 'San Francisco International Airport', '13');
insert into Airport values ('MEX', 'Mexico City International Airport', '14');
insert into Airport values ('LHR', 'Heathrow Airport', '15');
insert into Airport values ('LGW', 'Londen Gatwick Airport', '15');
insert into Airport values ('CDG', 'Charles de Gaulle Airport', '16');
insert into Airport values ('ORY', 'Paris Orly Airport', '16');
insert into Airport values ('FCO', 'Leonardo daVinci-Fiumicino Airport', '17');
insert into Airport values ('MUC', 'Munich Franz Josef Strauss Airport', '18');
insert into Airport values ('FRA', 'Frankfurt Airport', '19');
insert into Airport values ('MAD', 'Adolfo Suarez Madrid-Barajas Airport', '20');
insert into Airport values ('BCN', 'Josep Tarradellas Barcelona-El Prat Airport', '21');
insert into Airport values ('AMS', 'Schiphol Amsterdam Airport', '22');
insert into Airport values ('IST', 'Istanbul Airport', '23');
insert into Airport values ('DXB', 'Dubai International Airport', '24');
insert into Airport values ('DOH', 'Hamad International Airport', '25');
insert into Airport values ('HND', 'Tokyo Haneda Airport', '26');
insert into Airport values ('ICN', 'Incheon International Airport', '27');
insert into Airport values ('CAN', 'Guangzhou Baiyun International Airport', '28');
insert into Airport values ('SZX', "Shenzen Bao'an International Airport", '29');
insert into Airport values ('CTU', 'Chengdu Shuangliu International Airport', '30');
insert into Airport values ('PEK', 'Beijing Capital International Airport', '31');
insert into Airport values ('HKG', 'Hong Kong International Airport', '32');
insert into Airport values ('SYD', 'Sydney Kingsford Smith Airport', '33');
insert into Airport values ('MEL', 'Melbourne Airport', '34');
